FROM php:8.2-fpm-alpine

RUN apk add --no-cache bash git curl libpng-dev libzip-dev icu-dev oniguruma-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring zip intl gd

WORKDIR /var/www/html

COPY . .

EXPOSE 8000

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
